"""add_floor_calibration

Revision ID: 26243183572e
Revises: 9c88b780dc90
Create Date: 2026-08-22 11:19:25.124722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26243183572e'
down_revision: Union[str, Sequence[str], None] = '9c88b780dc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floors', sa.Column('anchor_1_lat', sa.Float(), nullable=True))
    op.add_column('floors', sa.Column('anchor_1_lng', sa.Float(), nullable=True))
    op.add_column('floors', sa.Column('anchor_1_x', sa.Float(), nullable=True))
    op.add_column('floors', sa.Column('anchor_1_y', sa.Float(), nullable=True))
    op.add_column('floors', sa.Column('anchor_2_lat', sa.Float(), nullable=True))
    op.add_column('floors', sa.Column('anchor_2_lng', sa.Float(), nullable=True))
    op.add_column('floors', sa.Column('anchor_2_x', sa.Float(), nullable=True))
    op.add_column('floors', sa.Column('anchor_2_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('floors', 'anchor_2_y')
    op.drop_column('floors', 'anchor_2_x')
    op.drop_column('floors', 'anchor_2_lng')
    op.drop_column('floors', 'anchor_2_lat')
    op.drop_column('floors', 'anchor_1_y')
    op.drop_column('floors', 'anchor_1_x')
    op.drop_column('floors', 'anchor_1_lng')
    op.drop_column('floors', 'anchor_1_lat')
    # ### end Alembic commands ###
