"""Add QRLocation and NavigationSession models

Revision ID: 9c88b780dc90
Revises: 3db658d2a2cd
Create Date: 2026-06-06 19:04:18.460231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c88b780dc90'
down_revision: Union[str, Sequence[str], None] = '3db658d2a2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navigation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('start_node_id', sa.String(), nullable=False),
    sa.Column('end_node_id', sa.String(), nullable=False),
    sa.Column('current_node_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['end_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['start_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('x_coordinate', sa.Float(), nullable=True),
    sa.Column('y_coordinate', sa.Float(), nullable=True),
    sa.Column('heading_direction', sa.Integer(), nullable=True),
    sa.Column('qr_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_locations_qr_code'), 'qr_locations', ['qr_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_locations_qr_code'), table_name='qr_locations')
    op.drop_table('qr_locations')
    op.drop_table('navigation_sessions')
    # ### end Alembic commands ###
